version: '3'

volumes:
  data:
services:
  grader:
    image: cse4100/run-mcc-mooc-grader
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/aplus:/tmp/aplus
      - .:/srv/courses/default
      - ./docker-compose-run.sh:/srv/docker-compose-run.sh
    ports:
      - "8080:8080"
  plus:
    image: apluslms/run-aplus-front:1.4
    volumes:
      - data:/data
    ports:
      - "8000:8000"
    depends_on:
      - grader

